from docx import Document
from docx.shared import Inches, Pt
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT
import io
from datetime import datetime


def generate_executive_profile_doc(profile_data, exec_id, currency_symbol="$"):
    """
    Generate a Word document with the executive profile.
    """
    doc = Document()
    doc.add_heading("Executive Profile", 0)

    # Basic info
    doc.add_heading("Personal Information", level=1)
    table = doc.add_table(rows=1, cols=2)
    table.style = 'Table Grid'
    hdr_cells = table.rows[0].cells
    hdr_cells[0].text = "Field"
    hdr_cells[1].text = "Value"

    fields = [
        ("Name", profile_data.get("Name", "")),
        ("Email", profile_data.get("Email", "")),
        ("Timezone", profile_data.get("Timezone", "")),
        ("Seat Preference", profile_data.get("Seat Preference", "")),
        ("Hotel Loyalty", profile_data.get("Hotel Loyalty", "")),
        ("Frequent Flyer", profile_data.get("Frequent Flyer", "")),
        ("Dietary", profile_data.get("Dietary", "")),
        ("Company", profile_data.get("Company", "")),
        ("Cost Center", profile_data.get("Cost Center", "")),
        ("Policy Notes", profile_data.get("Policy Notes", "")),
        ("Passport Number", profile_data.get("Passport Number", "")),
        ("Preferred Airline", profile_data.get("Preferred Airline", "")),
        ("TSA PreCheck", profile_data.get("TSA PreCheck", "")),
        ("Meal Preference", profile_data.get("Meal Preference", "")),
    ]

    for field, value in fields:
        row_cells = table.add_row().cells
        row_cells[0].text = field
        row_cells[1].text = str(value)

    # Memberships
    doc.add_heading("Memberships", level=1)
    mems = profile_data.get("Memberships", "")
    if mems:
        doc.add_paragraph(mems)
    else:
        doc.add_paragraph("No memberships recorded.")

    doc.add_page_break()
    doc.add_paragraph(f"Generated on {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    doc.add_paragraph("Executive Travel Planner")

    file_stream = io.BytesIO()
    doc.save(file_stream)
    file_stream.seek(0)
    return file_stream


def generate_itinerary_doc(
    exec_data,
    items,
    stops,
    dep_city,
    dep_region,
    dep_country,
    trip_id,
    trip_budget,
    display_symbol,
    display_currency,
    base_currency="USD",
    convert_to_base=False,
):
    """
    Generate a Word document with trip itinerary.
    """
    doc = Document()
    doc.add_heading(f"Itinerary: {exec_data['name']}", 0)

    # Trip overview
    doc.add_heading("Trip Overview", level=1)
    table = doc.add_table(rows=1, cols=2)
    table.style = 'Table Grid'
    hdr_cells = table.rows[0].cells
    hdr_cells[0].text = "Detail"
    hdr_cells[1].text = "Value"

    dep_parts = [p for p in [dep_city, dep_region, dep_country] if p]
    departure_display = ", ".join(dep_parts) if dep_parts else "Not specified"
    rows_data = [
        ("Executive", exec_data['name']),
        ("Departure", departure_display),
        ("Budget", f"{display_symbol}{trip_budget:.2f} {display_currency}"),
        ("Base Currency", base_currency),
    ]
    for label, value in rows_data:
        row_cells = table.add_row().cells
        row_cells[0].text = label
        row_cells[1].text = str(value)

    # Stops
    if stops:
        doc.add_heading("Stops", level=1)
        for stop in stops:
            loc = stop["city"]
            loc_parts = []
            if stop.get("region"):
                loc_parts.append(stop["region"])
            if stop.get("country"):
                loc_parts.append(stop["country"])
            if loc_parts:
                loc += f" ({', '.join(loc_parts)})"
            doc.add_paragraph(
                f"• {loc}: {stop['start_date']} to {stop['end_date']}",
                style='List Bullet'
            )

    # Itinerary items
    if items:
        doc.add_heading("Itinerary", level=1)
        table = doc.add_table(rows=1, cols=5)
        table.style = 'Table Grid'
        hdr_cells = table.rows[0].cells
        headers = ["Date/Time", "Type", "Description", "Location", "Cost"]
        for i, h in enumerate(headers):
            hdr_cells[i].text = h
            hdr_cells[i].paragraphs[0].runs[0].bold = True

        for item in items:
            row_cells = table.add_row().cells
            start_dt = datetime.fromisoformat(item['datetime_start'])
            row_cells[0].text = start_dt.strftime("%Y-%m-%d %H:%M")
            row_cells[1].text = item.get('item_type', '')
            row_cells[2].text = item.get('description', '')
            row_cells[3].text = item.get('location', '')
            cost = item.get('cost', 0)
            currency = item.get('cost_currency', 'USD')
            row_cells[4].text = f"{cost:.2f} {currency}"

    doc.add_page_break()
    doc.add_paragraph("Generated by Executive Travel Planner")
    file_stream = io.BytesIO()
    doc.save(file_stream)
    file_stream.seek(0)
    return file_stream, f"{exec_data['name']}_itinerary.docx"


def generate_expense_report_doc(
    exec_data,
    items,
    stops,
    dep_city,
    dep_region,
    dep_country,
    trip_id,
    trip_budget,
    trip_purpose,
    display_symbol,
    base_currency="USD",
):
    """
    Generate a Word document with expense report.
    """
    doc = Document()
    doc.add_heading(f"Expense Report: {trip_purpose}", 0)

    # Summary
    total_spent = sum(item.get('cost', 0) for item in items)
    confirmed_spent = sum(item.get('cost', 0) for item in items if item.get('is_confirmed', 0))
    estimated_spent = total_spent - confirmed_spent

    doc.add_heading("Summary", level=1)
    table = doc.add_table(rows=1, cols=2)
    table.style = 'Table Grid'
    hdr_cells = table.rows[0].cells
    hdr_cells[0].text = "Metric"
    hdr_cells[1].text = "Value"

    rows_data = [
        ("Total Budget", f"{display_symbol}{trip_budget:.2f} {base_currency}"),
        ("Total Spent", f"{display_symbol}{total_spent:.2f} {base_currency}"),
        ("Confirmed (Booked)", f"{display_symbol}{confirmed_spent:.2f} {base_currency}"),
        ("Estimated (Quoted)", f"{display_symbol}{estimated_spent:.2f} {base_currency}"),
        ("Remaining", f"{display_symbol}{trip_budget - total_spent:.2f} {base_currency}"),
    ]
    for label, value in rows_data:
        row_cells = table.add_row().cells
        row_cells[0].text = label
        row_cells[1].text = value

    # Itemized list
    doc.add_heading("Expense Details", level=1)
    if items:
        table = doc.add_table(rows=1, cols=6)
        table.style = 'Table Grid'
        hdr_cells = table.rows[0].cells
        headers = ["Date/Time", "Type", "Description", "Location", "Cost", "Confirmed"]
        for i, h in enumerate(headers):
            hdr_cells[i].text = h
            hdr_cells[i].paragraphs[0].runs[0].bold = True

        for item in items:
            row_cells = table.add_row().cells
            start_dt = datetime.fromisoformat(item['datetime_start'])
            row_cells[0].text = start_dt.strftime("%Y-%m-%d %H:%M")
            row_cells[1].text = item.get('item_type', '')
            row_cells[2].text = item.get('description', '')
            row_cells[3].text = item.get('location', '')
            cost = item.get('cost', 0)
            currency = item.get('cost_currency', 'USD')
            row_cells[4].text = f"{cost:.2f} {currency}"
            row_cells[5].text = "✅" if item.get('is_confirmed', 0) else "❌"
    else:
        doc.add_paragraph("No expenses recorded.")

    doc.add_page_break()
    doc.add_paragraph("Generated by Executive Travel Planner")
    file_stream = io.BytesIO()
    doc.save(file_stream)
    file_stream.seek(0)
    return file_stream, f"{exec_data['name']}_ExpenseReport.docx"


def generate_spending_report_doc(
    filter_label, summary_data, start_filter, end_filter, currency_symbol, base_currency="USD"
):
    """
    Generate a Word document with spending summary report.
    """
    doc = Document()
    doc.add_heading("Spending Report", 0)

    # Filter info
    doc.add_heading("Filters", level=1)
    doc.add_paragraph(f"Executive: {filter_label}")
    if start_filter:
        doc.add_paragraph(f"Start Date: {start_filter}")
    if end_filter:
        doc.add_paragraph(f"End Date: {end_filter}")
    doc.add_paragraph(f"Base Currency: {base_currency}")

    # Summary table
    doc.add_heading("Summary", level=1)
    if summary_data:
        table = doc.add_table(rows=1, cols=6)
        table.style = 'Table Grid'
        hdr_cells = table.rows[0].cells
        headers = ["Executive", "Destination", "Budget", "Total Spent", "Confirmed", "Status"]
        for i, h in enumerate(headers):
            hdr_cells[i].text = h
            hdr_cells[i].paragraphs[0].runs[0].bold = True

        for trip in summary_data:
            row_cells = table.add_row().cells
            row_cells[0].text = trip.get('executive_name', '')
            row_cells[1].text = trip.get('destination', '')
            row_cells[2].text = f"{currency_symbol}{trip.get('budget', 0):.2f}"
            row_cells[3].text = f"{currency_symbol}{trip.get('total_spent', 0):.2f}"
            row_cells[4].text = f"{currency_symbol}{trip.get('confirmed_spent', 0):.2f}"
            row_cells[5].text = trip.get('status', '').title()
    else:
        doc.add_paragraph("No trips found.")

    doc.add_page_break()
    doc.add_paragraph("Generated by Executive Travel Planner")
    file_stream = io.BytesIO()
    doc.save(file_stream)
    file_stream.seek(0)
    return file_stream


def generate_all_executive_profiles_doc(profiles):
    """
    Generate a Word document with a table of all executive profiles.
    """
    doc = Document()
    doc.add_heading("All Executive Profiles", 0)

    # Table header
    table = doc.add_table(rows=1, cols=8)
    table.style = 'Table Grid'
    hdr_cells = table.rows[0].cells
    headers = ["Name", "Email", "Company", "Timezone", "Seat", "Passport", "Memberships", "Meal"]
    for i, header in enumerate(headers):
        hdr_cells[i].text = header
        hdr_cells[i].paragraphs[0].runs[0].bold = True

    # Populate rows
    for p in profiles:
        row_cells = table.add_row().cells
        row_cells[0].text = p.get("Name") or ""
        row_cells[1].text = p.get("Email") or ""
        row_cells[2].text = p.get("Company") or ""
        row_cells[3].text = p.get("Timezone") or ""
        row_cells[4].text = p.get("Seat Preference") or ""
        row_cells[5].text = p.get("Passport Number") or ""
        row_cells[6].text = p.get("Memberships", "") or ""
        row_cells[7].text = p.get("Meal Preference") or ""

    doc.add_page_break()
    doc.add_paragraph("Generated by Executive Travel Planner")
    file_stream = io.BytesIO()
    doc.save(file_stream)
    file_stream.seek(0)
    return file_stream
